<div class="form-group<?=$errors['buildings'] ? ' has-error' : ''?>">
    <div><select name="building" class="form-control app-location-select-courier" data-sub-class="content-building-sub-rooms" data-sub-url="ajax/gatewaylocation/get-sub-rooms">
        <?php foreach ($buildings as $vBuilding) {?>
        <option value="<?=H($vBuilding['code'])?>"<?=$vBuilding['code']==$selected?' selected="selected"':''?>><?=H($vBuilding['name'])?></option>
        <?php }?>
    </select></div>
</div>
<div class="content-building-sub-rooms">
    <?=$room?>
</div>
