<?php
    $vError = is_null($multiKey) ? $errors['building'] : $errors['building'][$multiKey];
?>
<div class="form-group<?=$vError ? ' has-error' : ''?> col-xs-6" style="padding-left:0px;">
<div>
    <select
        name="<?=is_null($multiKey)?'building':"building[{$multiKey}]"?>"
        class="selectpicker form-control app-location-select-courier"
        data-sub-class="content-building-sub-rooms<?=is_null($multiKey)?'':"-{$multiKey}"?>"
        data-sub-url="ajax/gatewaylocation/get-sub-rooms"
        data-live-search="true"
        >
        <?php foreach ($buildings as $vBuilding) {?>
        <option value="<?=H($vBuilding['code'])?>"<?=$vBuilding['code']==$selected?' selected="selected"':''?>><?=H($vBuilding['name'])?></option>
        <?php }?>
    </select></div>
    <?php if ($vError) {?>
    <div class="text-right text-danger"><?=H($vError)?></div>
    <?php }?>
</div>
<div class="content-building-sub-rooms<?=is_null($multiKey)?'':"-{$multiKey}"?> col-xs-6" style="padding-left:0px;">
    <?=$room?>
</div>
