<?php 
	$vError = is_null($multiKey) ? $errors['room'] : $errors['room'][$multiKey];
?>
<div class="form-group<?=$vError ? ' has-error' : ''?>">
    <div>
        <?php if (empty($rooms)) { ?>
        <input type="text" class="form-control" name="<?=H(is_null($multiKey)?'room':"room[{$multiKey}]")?>" value="<?=H($selected)?>" placeholder="<?= H(T('请填写房间号'))?>" />
        <?php } else { ?>
        <select name="<?=H(is_null($multiKey)?'room':"room[{$multiKey}]")?>" 
        class="selectpicker form-control"
        data-live-search="true"
        >
            <?php foreach ($rooms as $vRoom) {?>
            <option value="<?=H($vRoom['name'])?>"<?=$vRoom['name']==$selected?' selected="selected"':''?>><?=H($vRoom['name'])?></option>
            <?php }?>
        </select>
        <?php }?>
    </div>
	<?php if ($vError) {?>
	<div class="text-right text-danger"><?=H($vError)?></div>
	<?php }?>
</div>
