<?php 
$checkActive = function($routeCheckings) use($route) {
    foreach ($routeCheckings as $routeChecking) {
        if (0 == strncmp($routeChecking, $route, strlen($routeChecking))) {
            return ' class="active"';
        }
    }
};
if ($currentAppID==$clients['lab-orders']) {
?>
<div class="menu-item">
    <a href="home" <?= $checkActive(['home', 'search', 'product', 'vendors', 'vendor'])?>><i class="fa fa-fw fa-shopping-cart"></i> &nbsp;<?= H(T('我要采购')) ?></a>
</div>
<div class="menu-item">
    <a href="order/history" <?= $checkActive(['order/history'])?>><i class="fa fa-fw fa-list"></i> &nbsp;<?= H(T('订单列表')) ?></a>
</div>
<?php /* ($me->isAllowedTo('订单支付', 'order')) */?>
<div class="menu-item">
    <a href="payment/history" <?= $checkActive(['payment/history'])?>><i class="fa fa-fw fa-credit-card"></i> &nbsp;<?= H(T('付款管理')) ?></a>
</div>
<?php } else { ?>
<div class="menu-item">
    <a href="gapper/client/go/<?=H($app_id)?>/<?=$group->id?>?redirect=home"><i class="fa fa-fw fa-shopping-cart"></i> &nbsp;<?= H(T('我要采购')) ?></a>
</div>
<div class="menu-item">
    <a href="gapper/client/go/<?=H($app_id)?>/<?=$group->id?>?redirect=order/history"><i class="fa fa-fw fa-list"></i> &nbsp;<?= H(T('订单列表')) ?></a>
</div>
<div class="menu-item">
    <a href="gapper/client/go/<?=H($app_id)?>/<?=$group->id?>?redirect=payment/history"><i class="fa fa-fw fa-credit-card"></i> &nbsp;<?= H(T('付款管理')) ?></a>
</div>
<?php }?>

